

name: roni




-*roni*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
    - name: REST API with curl
    run: 
    curl -X GET "https://twitter.com/ilovemsii"
     
      - uses: actions/checkout@v2

     
      - name: Run a one-line script
run:


 
      - name: Run a multi-line script
        run: |

