

name: test 2




-*gigachad*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
    - name: REST API with curl
    run: 
curl --request GET 'https://api.twitter.com/2/tweets/search/recent?query=from:ilovemsii'


     
      - uses: actions/checkout@v2

     
      - name: Run a one-line script
run:


 
      - name: Run a multi-line script
        run: |

